version: 2
jobs:
  build:
    working_directory: ~/PopCorn2
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run Lint Checks
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Decode Keystore
          command: echo $KEYSTORE_BASE64 | base64 --decode > keystore.jks
      - run:
          name: Build Apps
          command: ./gradlew assemble

      - run:
          name: Run Test Coverage
          command: ./gradlew jacocoTestReport
      - run:
          name: Upload Test Coverage Reports
          command: bash <(curl -s https://codecov.io/bash) -Z

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: builds

      - store_test_results:
          path: app/build/test-results
